name: Hello Workflow

on: 
  push: 
    branches:
     - main 

jobs: 
   job1:
     runs-on: ubuntu-latest
     steps :
      - run: echo "hello world"

      job2:
        runs-on: ubuntu-latest
        steps:
        -run: echo " second job successful"
